### ISSUE TITLE
date and number formatting

### ISSUE THREAD

**Issue by alicebob** [TheDataShed/xlsxreader#25]
Hi!

Two more things, they are related, so I'll make them a single issue:

- date formatting is currently hardcoded to use the format time.RFC3339 (for a datetime) or `"2006-01-02"` (for a date). That's a very reasonable choice, however for (boring business) reasons I need to be able to format a date differently.
- `Cell.Value` is currently not changed from what's stored in the file, which means that for numbers it will be in scientific notation when they are "big". Our xlsx have phone numbers in them, and are uploaded by customers. Those _should_ be stored by our customers as strings, but you know, sometimes they aren't, and then they end up as `1.23456789E8`. So I need to reformat numbers with `strconv.ParseFloat(...); strconv.FormatFloat(f, 'f', -1, 64)`.

## how about

How about we define constants for the possible cell types: [string, numerical, datetime, date, boolean] (more?) and add a field with the cell type to the `Cell` struct.
That way I can parse and reformat numerical types how I see fit, and same with date cells: parse them as `2006-01-02` and then reformat them how I want.
Adding a custom type, as opposed to exposing the raw xlsx cell type, makes there is no distinction between 'inline strings' and normal strings, and makes it clear what's a datetime/date.

I'm happy to make an example PR, but I didn't want to submit it out of the blue.

Thanks!

**Comment by dglsparsons** [comment]
It might make some sense to have some helper methods based on the various types. 

i.e. Cell.AsTime() -> returns a time.Time{} struct, rather than ISO String. 
Ditto for Boolean / Numerical (int vs float could be interesting though).
