### ISSUE TITLE
Merged Cells

### ISSUE THREAD

**Issue by OmarAyadi** [TheDataShed/xlsxreader#44]
Is there a way in the library to view merged cells, because at the moment the library skips the merged cells and return them as empty.

**Comment by dglsparsons** [comment]
I'm not aware of how merged cells are represented within the XML document itself. 

I'd suspect the first cell contains a value, but the rest are empty? Would be good to confirm though. 

It's not something we've explicitly looked at for this library so far - we just reflect the structure of the XML document in what is returned.

**Comment by nathj07** [comment]
I'm currently evaluating this library and I see that merged cells do seem to get extracted. 
<img width="340" alt="Screenshot 2023-01-23 at 10 32 42" src="https://user-images.githubusercontent.com/3279761/214018419-99f31632-1a12-4f70-b857-a34a329888e0.png">

This gets extracted as:
```
{A 1 General Objective
To test the impact of mixed font styles in one set of mixed cell
We'll also look at colour and font variance string}     

{A 3 Key
Purple text
Orange text
Green text string} 
```
That seems about right to me. Thought I'd comment on this old issue in case it was helpful
