### ISSUE TITLE
proposal: fix goroutine leaks when calling ReadRows

### ISSUE THREAD

**Issue by muktihari** [TheDataShed/xlsxreader#56]
This is well-known issue since it is documented in the code but actually the fix is simple. But first, let me explain the issue to give more context for anyone reading this proposal:

When we only want to read some rows using `ReadRows`, we have to read the whole rows in the sheet, otherwise, it will produce a goroutine leaks. The goroutine leaks will never be clean up and will only be accumulated until the program exit. This happen because `ReadRows` spawned a goroutine that will always try to send the data to a non-buffered channel `rowChannel` but there are no longer readers at the other end:
https://github.com/TheDataShed/xlsxreader/blob/f3dd3aee1ed1cca6881e371b21e244df1227e543/rows.go#L363-L367
https://github.com/TheDataShed/xlsxreader/blob/f3dd3aee1ed1cca6881e371b21e244df1227e543/rows.go#L258
https://github.com/TheDataShed/xlsxreader/blob/f3dd3aee1ed1cca6881e371b21e244df1227e543/rows.go#L286-L294

Leaks proof:
```go
func TestGoroutineLeaks(t *testing.T) {
	goroutineUsedByTest := runtime.NumGoroutine()

	xl, err := OpenFile("test/test-small.xlsx")
	if err != nil {
		t.Fatal(err)
	}

	row := <-xl.ReadRows(xl.Sheets[0])
	_ = row // pull one row

	ng := runtime.NumGoroutine() - goroutineUsedByTest
	t.Logf("active goroutine before: %d\n", ng)

	xl.Close()   // Close XlsxFile
	runtime.GC() // Force GC to run

	ng = runtime.NumGoroutine() - goroutineUsedByTest

	t.Logf("active goroutine after: %d\n", ng)

	if ng != 0 {
		t.Fatalf("expected active goroutine is zero, got: %d", ng)
	}
}
```

Even though the XlsxFIle has been closed and no longer used, runtime could not clean it up.

If left unaddressed, this issue will compromise the integrity of this library slogan: "A low-memory high performance library for reading data from an xlsx file.". 

The memory leaks may contradict with "low-memory" claim, and if users are compelled to read entire rows unnecessarily, their program performance will suffer especially if the xlsx file is huge in size, this may contradict with "high performance" claim.

So, here is the fix: 
- We need to make `x.readSheetRows` aware when user is calling Close(), all operations should be dropped:
```go
if startElement.Name.Local == "row" {
        row := x.parseRow(decoder, &startElement)
        if len(row.Cells) < 1 && row.Error == nil {
	        continue
        }
        select {
        case <-x.doneChannel:
	        return
        case ch <- row:
        }
}
```

If this proposal is being accepted, I will send the PR with proper test so you can review it.

**Comment by dglsparsons** [comment]
I'm very happy to accept this. Although no longer the maintainer of this codebase. 

CC @AndyThurgood for privileges.

**Comment by muktihari** [comment]
Hi @dglsparsons, I just send the PR and mention @AndyThurgood as the maintainer, thank you!
