### ISSUE TITLE
xml/unmarshal/rawcell: Is this float64 rounding really necessary?

### ISSUE THREAD

**Issue by muktihari** [TheDataShed/xlsxreader#59]
Hi @KingMichaelPark, is this float64 rounding really necessary?
https://github.com/TheDataShed/xlsxreader/blob/6f2298af535f51afe054ddeaa9336563aa04215f/rows.go#L235-L240

What I can see from issue #55 is that the problem is in the file itself, not this library. The value in the file is indeed "4.4000000000000004" not "4.4". Using vscode' debug:

![xlsxreader-debug](https://github.com/TheDataShed/xlsxreader/assets/15964188/8b6b98d7-55a0-4dc2-a0d6-c7a19e4c7bbe)

Or, if you prefer to look at xml file directly, we can extract like this:
```go
package main

import (
	"archive/zip"
	"io"
	"os"
)

func main() {
	f, err := zip.OpenReader("file1.xlsx")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	out, err := os.OpenFile("debug_file1.xlsx_sheet1.xml", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
	if err != nil {
		panic(err)
	}
	defer out.Close()

	for _, file := range f.File {
		if file.Name == "xl/worksheets/sheet1.xml" {
			sheet1, err := file.Open()
			if err != nil {
				panic(err)
			}
			_, err = io.Copy(out, sheet1)
			if err != nil {
				sheet1.Close()
				panic(err)
			}
			sheet1.Close()
			break
		}
	}
}

```

Here is the resulting file:  [debug_file1.xlsx_sheet1.xml.zip](https://github.com/user-attachments/files/15522506/debug_file1.xlsx_sheet1.xml.zip)

I'm afraid it might affect performance since we need to re-alloc string twice, it's small but remember it's per affected cell:
```go
func BenchmarkParseFloatRoundTrip(b *testing.B) {
	v := "4.4000000000000004"
	for i := 0; i < b.N; i++ {
		v2, _ := strconv.ParseFloat(v, 64)
		_ = strconv.FormatFloat(v2, 'f', -1, 64)
	}
}
// Output:
// BenchmarkParseFloatRoundTrip-4    3446553    342.2 ns/op	   27 B/op    2 allocs/op 
```

I believe this floating-point handling should be placed at user space rather than in this library since they are the one who own the file so they are expected to know how to manage. Moreover, it's the nature of floating-point number to have that kind of precision, it's expected.

CMIIW.

**Comment by KingMichaelPark** [comment]
reverted, I did the lazy way of checking and other parsing libraries coerced it automatically as well so followed that pattern but you've convinced me. Cheers @muktihari
